from __future__ import annotations

from dataclasses import dataclass
from unicodedata import normalize

from app.domain.document.models.bounding_box import BoundingBox
from app.domain.document.models.font import Font


@dataclass(frozen=True, slots=True)
class TextSpan:
    """
    Immutable textual region observed in a document page.

    A TextSpan stores only objective information extracted from the
    document: the original text, its position, its font and the page
    where it was found.

    The model does not determine whether the text is hidden, suspicious,
    fraudulent, generated by OCR or related to prompt injection.
    """

    text: str
    bounding_box: BoundingBox
    font: Font
    page_number: int

    def __post_init__(self) -> None:
        if not isinstance(self.text, str):
            raise TypeError(
                "TextSpan text must be a string."
            )

        if not isinstance(self.bounding_box, BoundingBox):
            raise TypeError(
                "TextSpan bounding_box must be a BoundingBox."
            )

        if not isinstance(self.font, Font):
            raise TypeError(
                "TextSpan font must be a Font."
            )

        normalized_page_number = self._normalize_page_number(
            self.page_number
        )

        object.__setattr__(
            self,
            "page_number",
            normalized_page_number,
        )

    @property
    def normalized_text(self) -> str:
        """
        Return a comparison-friendly representation of the text.

        Unicode compatibility normalization is applied and consecutive
        whitespace characters are collapsed into a single space.

        The original text stored in the object is never modified.
        """

        unicode_normalized = normalize(
            "NFKC",
            self.text,
        )

        return " ".join(
            unicode_normalized.split()
        )

    @property
    def normalized_casefold_text(self) -> str:
        """
        Return normalized text using case-insensitive normalization.
        """

        return self.normalized_text.casefold()

    @property
    def character_count(self) -> int:
        """
        Return the number of characters in the original text.

        Whitespace and control characters are included.
        """

        return len(self.text)

    @property
    def normalized_character_count(self) -> int:
        """
        Return the number of characters after text normalization.
        """

        return len(self.normalized_text)

    @property
    def word_count(self) -> int:
        """
        Return the number of whitespace-delimited words.
        """

        if not self.normalized_text:
            return 0

        return len(
            self.normalized_text.split(" ")
        )

    @property
    def is_empty(self) -> bool:
        """
        Return whether the original text contains no characters.
        """

        return self.text == ""

    @property
    def is_whitespace(self) -> bool:
        """
        Return whether the text is empty or contains only whitespace.
        """

        return not self.text.strip()

    @property
    def has_visible_text(self) -> bool:
        """
        Return whether the text contains at least one non-whitespace
        character.

        This property describes textual content only. It does not inspect
        font color, opacity, clipping, layers or page visibility.
        """

        return not self.is_whitespace

    @staticmethod
    def _normalize_page_number(value: int) -> int:
        if isinstance(value, bool) or not isinstance(value, int):
            raise TypeError(
                "TextSpan page_number must be an integer."
            )

        if value < 1:
            raise ValueError(
                "TextSpan page_number must be greater than or equal to 1."
            )

        return value